bbs/urls.py
from django.urls import path
from . import views

app_name    = "bbs"
urlpatterns = [ 
    path('', views.index, name="index"),
    path('<int:pk>/', views.index, name="single"),

    path('refresh/', views.refresh, name="refresh"),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("bbs.urls"), name="bbs"),
]

bbs/models.py
from django.db import models
from django.utils import timezone

class Topic(models.Model):
    
    #ロングポーリングを実現させるためには、order_byは必須。並び替えを機能させるために、投稿日時を記録するフィールドを追加しておく。

    dt      = models.DateTimeField(verbose_name="投稿日時",default=timezone.now)
    comment = models.CharField(verbose_name="コメント",max_length=2000)

    def __str__(self):
        return self.comment

bbs/forms.py
from django import forms
from .models import Topic

class TopicForm(forms.ModelForm):

    class Meta:
        model   = Topic
        fields  = [ "comment" ]


#ロングポーリング用のフォームクラス
class TopicFirstForm(forms.Form):

    #Topicのidに基づく
    first   = forms.IntegerField(required=False)

bbs/views.py
from django.shortcuts import render

from django.views import View

from django.http.response import JsonResponse
from django.template.loader import render_to_string

from .models import Topic
from .forms import TopicForm,TopicFirstForm


import time

class IndexView(View):
    
    def render_content(self,request):
        topics          = Topic.objects.order_by("-dt")
        context         = { "topics":topics }

        return render_to_string("bbs/content.html",context,request)

    def get(self, request, *args, **kwargs):

        topics  = Topic.objects.order_by("-dt")
        context = { "topics":topics }

        return render(request,"bbs/index.html",context)

    def post(self, request, *args, **kwargs):

        data    = { "error":True }
        form    = TopicForm(request.POST)

        if not form.is_valid():
            print(form.errors)
            return JsonResponse(data)

        form.save()

        data["error"]   = False
        data["content"] = self.render_content(request)

        return JsonResponse(data)

    def delete(self, request, *args, **kwargs):
        
        data    = { "error":True }

        if "pk" not in kwargs:
            return JsonResponse(data)

        topic   = Topic.objects.filter(id=kwargs["pk"]).first()

        if not topic:
            return JsonResponse(data)

        topic.delete()

        data["error"]   = False
        data["content"] = self.render_content(request)

        return JsonResponse(data)

index   = IndexView.as_view()


# ロングポーリング
class RefreshView(View):

    def get(self, request, *args, **kwargs):

        data    = { "error":True }

        form    = TopicFirstForm(request.GET)
        
        #XXX:誰も何も投稿していない場合、firstに来る値は何もないので、必ずバリデーションエラーになってしまう。
        #未投稿の状況でもロングポーリングをさせるには、nullを許可する必要が有ると思われる。
        if not form.is_valid():
            print(form.errors)
            return JsonResponse(data)

        cleaned         = form.clean()

        first_id        = None
        if "first" in cleaned:
            first_id    = cleaned["first"]


        #30回ループする。(1秒おきにDBにアクセスする)
        #CHECK:このループは最大で30秒間レスポンスを返さないことを意味しているので、ブラウザのタイムアウトを考慮して調整する必要が有る。
        for i in range(30):

            topic   = Topic.objects.order_by("-dt").first()

            #topicが存在しており、そのtopicがかつての最新のものと違う場合、ループを抜ける。
            if topic:
                if topic.id != first_id:
                    break
            else:
                #かつての最新の投稿がNoneではない場合、削除されたことを意味するので、この場合もループを抜ける
                if first_id != None:
                    break

            time.sleep(1)
            #print("ロングポーリング中")


        topics  = Topic.objects.order_by("-dt")
        context = { "topics":topics }

        data["error"]   = False
        data["content"] = render_to_string("bbs/content.html",context,request)

        return JsonResponse(data)

refresh = RefreshView.as_view()

templates/bbs/content.html
{% for topic in topics %}

{% if forloop.first %}
<input id="first" type="hidden" value="{{ topic.id }}" name="first">
{% endif %}


<div class="border">
    <div>{{ topic.dt }}</div>
    <div>{{ topic.comment }}</div>
    <form action="{% url 'bbs:single' topic.id %}">
        <input class="btn btn-outline-danger trash" type="button" value="削除">
    </form>
</div>
{% empty %}
<input id="first" type="hidden" value="" name="first">


{% endfor %}

templates/bbs/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
	<title>簡易掲示板</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

    {# Ajaxを送信する時、ヘッダにCSRFトークンをセットする。 #}
    <script src="{% static 'js/ajax.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>

</head>
<body>

    <main class="container">
        <form id="form_area" action="" method="POST">
            {# FormDataでformタグの中身全部を取った時、CSRFトークンもセットで取れるので、Forbiddenにならない #}
            {% csrf_token %}
            <textarea id="textarea" class="form-control" name="comment"></textarea>
            <input id="submit_form" type="button" value="送信">
        </form>

        <div id="content_area">{% include "bbs/content.html" %}</div>

    </main>
</body>
</html>